apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.servertargetPort }}
    nodePort: {{ .Values.service.servernodeport }}
  selector:
    app: server
    tier: backend
  type: {{ .Values.service.type }}
status:
  loadBalancer: {}